# Generated by Django 5.1.1 on 2024-09-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_match_player1_alter_match_player2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournoi',
            name='winner',
            field=models.CharField(max_length=200),
        ),
    ]
