# Generated by Django 5.1.1 on 2024-09-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_tournoi_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournoi',
            name='winner',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
