# Generated by Django 5.1.1 on 2024-09-14 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_tournoi_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='num_won_tournaments',
        ),
    ]
